feature_list = [
'price', 
'picture', 
'battery', 
'storage', 
'general',
# 'upgrade', 
# 'hardware', 
'software', 
'size', 
'design', 
'video', 
'service', 
# 'help-care', 
# 'overall', 
'lens', 
'focus', 
'exposure', 
'shutter'
]
processed_data = [
['rate','worth', 'set', 'price','cost', 'value', 'money','cheap','expensive','budget','dollar','bill','cash','affordability'], 
['picture', 'image', 'photo', 'exposure', 'scene', 'pic', 'photograph', 'impression', 'painting','shot'], 
['battery','charge','adapter', 'backup','time','worktime','standby','power','supply'],
['store', 'hardware', 'memory', 'ram', 'capacity', 'processor','disk'], 
['overall','everything','build','damage','use','utility','features','stuff','recommend','product','usage','unit'], 
#['software', 'range', 'order', 'hardware', 'better', 'place', 'package', 'rank', 'rate', 'advance', 'side'],
# ['hardware', 'component', 'screen', 'display', 'dial', 'key', 'button','panel','lcd','accessory'], 
['performance','delay','freeze','hot','auto','automode','lag','setup','automatic','settings','chip','fast','advanced','drivers','processing'],
# ['picture', 'feature', 'movie', 'film', 'pic', 'product', 'have', 'boast', 'sport'],
['small', 'weigh', 'light', 'massive', 'bulky', 'heavy','huge','weight','fit','smallest'], 
['surface','design', 'system', 'program', 'aim', 'make','texture','construction','build','solid','look','body','feel','case','color','silver','leather','casing','strap','pouch','designed','durable'],
['video','movie','film','shoot','shooting','sound', 'audio','microphone','mic','media','video-quality'], 
['work', 'couple', 'company', 'service', 'tune', 'servicing', 'assist', 'personnel', 'delivery', 'service','support', 'help','care','trust','maintance','shipping','reliability'],
# ['support', 'help','care','trust','maintance'], 
# [],
['zoom','line', 'lense', 'lens','resolution', 'mp', 'megapixel','viewfinder','zooming'],
['focus', 'focusing', 'set', 'direction', 'point', 'sharpness', 'center', 'clarity', 'adjust', 'centre','grain','noise','shape','distortion','sharp'],
['photography', 'exposure', 'scene', 'view', 'photograph', 'panorama','lighting','aperture','dark','night','white'], 
['shutter', 'screen','speed']
]
