feature_list = ['price', 'picture', 'battery', 'storage', 'upgrade', 'hardware', 'feature', 'size', 'design', 'media', 'sound', 'service', 'help-care', 'overall', 'lens', 'focus', 'exposure', 'shutter','general']
processed_data = [['worth', 'set', 'price', 'damage', 'cost', 'value', 'money','cheap','expensive','budget'], 
['picture', 'image', 'movie', 'video', 'photo', 'exposure', 'film', 'scene', 'pic', 'photograph', 'impression', 'see', 'painting', 'resolution', 'mp', 'megapixel'], 
['battery','charge','adapter', 'backup'],
 ['store', 'hardware', 'memory', 'business', 'build', 'ram', 'capacity', 'processor'], 
 ['software', 'range', 'order', 'hardware', 'better', 'place', 'package', 'rank', 'rate', 'advance', 'side'],
['hardware', 'component', 'screen', 'display', 'dial', 'key', 'button'], 
 ['picture', 'feature', 'movie', 'film', 'pic', 'product', 'have', 'boast', 'sport'],
  ['size', 'sort', 'class', 'situation', 'surface','small', 'weigh', 'light', 'massive', 'bulky', 'heavy'], 
  ['design', 'system', 'program', 'think', 'end', 'plan', 'purpose', 'mean', 'aim', 'make'],
   ['line', 'job', 'substance', 'medium', 'environment', 'environs', 'business', 'state'],
    ['sound', 'audio'], 
    ['work', 'couple', 'function', 'go', 'company', 'service', 'care', 'help', 'tune', 'servicing', 'assist', 'run', 'personnel', 'delivery', 'Service', 'force'],
     ['support', 'help','care','trust','maintance'], 
     [],
      ['line', 'lense', 'lens'],
       ['focus', 'focusing', 'set', 'direction', 'point', 'think', 'sharpness', 'center', 'clarity', 'adjust', 'centre'],
        ['picture', 'photo', 'photography', 'exposure', 'scene', 'view', 'pic', 'photograph', 'panorama'], 
        ['shutter', 'screen']
        ,[]]
