$(function(){
var nodes_1 = [
{id: 1, label: "size"},
{id: 2, label: "compact"},
{id: 3, label: "size"},
{id: 4, label: "highest"},
{id: 5, label: "priority"},
{id: 6, label: "camera"},
{id: 7, label: "canon"},
{id: 8, label: "powershot"},
{id: 9, label: "s100"},
{id: 10, label: "digital"},
{id: 11, label: "elph"},
{id: 12, label: "standout"},
{id: 13, label: "choice"},
{id: 14, label: "aptly"},
{id: 15, label: "diminutive"},
{id: 16, label: "design"},
{id: 17, label: "first"},
{id: 18, label: "really"},
{id: 19, label: "tiny"},
{id: 20, label: "pack"},
{id: 21, label: "cigarettes"},
{id: 22, label: "scooch"},
{id: 23, label: "deeper"},
];
var edges_1 = [
{from: 1, to: 2},
{from: 1, to: 3},
{from: 1, to: 4},
{from: 1, to: 5},
{from: 1, to: 6},
{from: 1, to: 7},
{from: 1, to: 8},
{from: 1, to: 9},
{from: 1, to: 10},
{from: 1, to: 11},
{from: 1, to: 12},
{from: 1, to: 13},
{from: 1, to: 14},
{from: 1, to: 15},
{from: 1, to: 16},
{from: 1, to: 17},
{from: 1, to: 18},
{from: 1, to: 19},
{from: 1, to: 20},
{from: 1, to: 21},
{from: 1, to: 22},
{from: 1, to: 23},
];
var container_1 = document.getElementById("container_1");
var data_1= {
nodes: nodes_1,
edges: edges_1
};
var options_1 = {
width: "600px",
height: "600px"
};
var network_1 = new vis.Network(container_1, data_1, options_1);
});
$(function(){
var nodes_2 = [
{id: 1, label: "focus"},
{id: 2, label: "razor"},
{id: 3, label: "sharp"},
{id: 4, label: "color"},
{id: 5, label: "balance"},
{id: 6, label: "perfect"},
{id: 7, label: "focus"},
{id: 8, label: "great"},
];
var edges_2 = [
{from: 1, to: 2},
{from: 1, to: 3},
{from: 1, to: 4},
{from: 1, to: 5},
{from: 1, to: 6},
{from: 1, to: 7},
{from: 1, to: 8},
];
var container_2 = document.getElementById("container_2");
var data_2= {
nodes: nodes_2,
edges: edges_2
};
var options_2 = {
width: "600px",
height: "600px"
};
var network_2 = new vis.Network(container_2, data_2, options_2);
});
$(function(){
var nodes_3 = [
{id: 1, label: "picture"},
{id: 2, label: "good"},
{id: 3, label: "small"},
{id: 4, label: "size"},
{id: 5, label: "durable-seeming"},
{id: 6, label: "metal"},
{id: 7, label: "case"},
{id: 8, label: "easy"},
{id: 9, label: "visually"},
{id: 10, label: "distinctive"},
{id: 11, label: "picture"},
{id: 12, label: "quality"},
{id: 13, label: "fast"},
{id: 14, label: "usb"},
{id: 15, label: "connection"},
{id: 16, label: "mostly"},
{id: 17, label: "intuitive"},
{id: 18, label: "operation"},
{id: 19, label: "really"},
{id: 20, label: "cool"},
{id: 21, label: "photostitch"},
{id: 22, label: "software"},
{id: 23, label: "pictures"},
{id: 24, label: "together"},
{id: 25, label: "wide"},
{id: 26, label: "panoramas"},
{id: 27, label: "s100s"},
{id: 28, label: "image"},
{id: 29, label: "rates"},
{id: 30, label: "middle"},
{id: 31, label: "class"},
{id: 32, label: "still"},
{id: 33, label: "reasonable"},
{id: 34, label: "choice"},
{id: 35, label: "students"},
{id: 36, label: "families"},
{id: 37, label: "businesses"},
{id: 38, label: "ultra-portable"},
{id: 39, label: "camera"},
{id: 40, label: "pound"},
{id: 41, label: "media"},
{id: 42, label: "battery"},
{id: 43, label: "pack"},
{id: 44, label: "sale"},
{id: 45, label: "extra"},
{id: 46, label: "$$$"},
{id: 47, label: "definitely"},
{id: 48, label: "worth"},
{id: 49, label: "first"},
{id: 50, label: "never"},
{id: 51, label: "slightest"},
{id: 52, label: "problem"},
{id: 53, label: "solid"},
{id: 54, label: "performs"},
{id: 55, label: "well"},
{id: 56, label: "lasts"},
{id: 57, label: "pretty"},
{id: 58, label: "long"},
{id: 59, label: "lcd"},
{id: 60, label: "viewfinder"},
{id: 61, label: "little"},
{id: 62, label: "people"},
{id: 63, label: "however"},
{id: 64, label: "flaw"},
{id: 65, label: "subjects"},
{id: 66, label: "skin"},
{id: 67, label: "also"},
{id: 68, label: "very"},
{id: 69, label: "moment"},
{id: 70, label: "digital"},
{id: 71, label: "processing"},
{id: 72, label: "time"},
{id: 73, label: "press"},
{id: 74, label: "button"},
{id: 75, label: "actually"},
{id: 76, label: "coolest"},
{id: 77, label: "ive"},
{id: 78, label: "ever"},
{id: 79, label: "second"},
{id: 80, label: "incredibly"},
{id: 81, label: "just"},
{id: 82, label: "quick"},
{id: 83, label: "photo"},
{id: 84, label: "shoot"},
{id: 85, label: "nycs"},
{id: 86, label: "central"},
{id: 87, label: "park"},
{id: 88, label: "today"},
{id: 89, label: "bunch"},
{id: 90, label: "beautiful"},
{id: 91, label: "photos"},
{id: 92, label: "so"},
{id: 93, label: "point"},
{id: 94, label: "instant"},
{id: 95, label: "review"},
{id: 96, label: "screen"},
{id: 97, label: "shots"},
{id: 98, label: "spot"},
];
var edges_3 = [
{from: 1, to: 2},
{from: 1, to: 3},
{from: 1, to: 4},
{from: 1, to: 5},
{from: 1, to: 6},
{from: 1, to: 7},
{from: 1, to: 8},
{from: 1, to: 9},
{from: 1, to: 10},
{from: 1, to: 11},
{from: 1, to: 12},
{from: 1, to: 13},
{from: 1, to: 14},
{from: 1, to: 15},
{from: 1, to: 16},
{from: 1, to: 17},
{from: 1, to: 18},
{from: 1, to: 19},
{from: 1, to: 20},
{from: 1, to: 21},
{from: 1, to: 22},
{from: 1, to: 23},
{from: 1, to: 24},
{from: 1, to: 25},
{from: 1, to: 26},
{from: 1, to: 27},
{from: 1, to: 28},
{from: 1, to: 29},
{from: 1, to: 30},
{from: 1, to: 31},
{from: 1, to: 32},
{from: 1, to: 33},
{from: 1, to: 34},
{from: 1, to: 35},
{from: 1, to: 36},
{from: 1, to: 37},
{from: 1, to: 38},
{from: 1, to: 39},
{from: 1, to: 40},
{from: 1, to: 41},
{from: 1, to: 42},
{from: 1, to: 43},
{from: 1, to: 44},
{from: 1, to: 45},
{from: 1, to: 46},
{from: 1, to: 47},
{from: 1, to: 48},
{from: 1, to: 49},
{from: 1, to: 50},
{from: 1, to: 51},
{from: 1, to: 52},
{from: 1, to: 53},
{from: 1, to: 54},
{from: 1, to: 55},
{from: 1, to: 56},
{from: 1, to: 57},
{from: 1, to: 58},
{from: 1, to: 59},
{from: 1, to: 60},
{from: 1, to: 61},
{from: 1, to: 62},
{from: 1, to: 63},
{from: 1, to: 64},
{from: 1, to: 65},
{from: 1, to: 66},
{from: 1, to: 67},
{from: 1, to: 68},
{from: 1, to: 69},
{from: 1, to: 70},
{from: 1, to: 71},
{from: 1, to: 72},
{from: 1, to: 73},
{from: 1, to: 74},
{from: 1, to: 75},
{from: 1, to: 76},
{from: 1, to: 77},
{from: 1, to: 78},
{from: 1, to: 79},
{from: 1, to: 80},
{from: 1, to: 81},
{from: 1, to: 82},
{from: 1, to: 83},
{from: 1, to: 84},
{from: 1, to: 85},
{from: 1, to: 86},
{from: 1, to: 87},
{from: 1, to: 88},
{from: 1, to: 89},
{from: 1, to: 90},
{from: 1, to: 91},
{from: 1, to: 92},
{from: 1, to: 93},
{from: 1, to: 94},
{from: 1, to: 95},
{from: 1, to: 96},
{from: 1, to: 97},
{from: 1, to: 98},
];
var container_3 = document.getElementById("container_3");
var data_3= {
nodes: nodes_3,
edges: edges_3
};
var options_3 = {
width: "600px",
height: "600px"
};
var network_3 = new vis.Network(container_3, data_3, options_3);
});
$(function(){
var nodes_4 = [
{id: 1, label: "lens"},
{id: 2, label: "two-times"},
{id: 3, label: "optical"},
{id: 4, label: "zoom"},
{id: 5, label: "smoothly"},
{id: 6, label: "quietly"},
{id: 7, label: "two-piece"},
{id: 8, label: "shutter-like"},
{id: 9, label: "cap"},
{id: 10, label: "automatically"},
{id: 11, label: "lens"},
{id: 12, label: "camera"},
];
var edges_4 = [
{from: 1, to: 2},
{from: 1, to: 3},
{from: 1, to: 4},
{from: 1, to: 5},
{from: 1, to: 6},
{from: 1, to: 7},
{from: 1, to: 8},
{from: 1, to: 9},
{from: 1, to: 10},
{from: 1, to: 11},
{from: 1, to: 12},
];
var container_4 = document.getElementById("container_4");
var data_4= {
nodes: nodes_4,
edges: edges_4
};
var options_4 = {
width: "600px",
height: "600px"
};
var network_4 = new vis.Network(container_4, data_4, options_4);
});
